name: Unit Tests - Stage Branch

on:
  pull_request:
    types: [opened , reopened]
    branches:
      - 'stage'

  workflow_dispatch: # Allows manual triggering from the UI

jobs:
  pydantic_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.3"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install dependancies
        run: uv sync --locked --all-extras --dev

      - name: Run Ruff Checks
        run: uv run ruff check

      - name: Run Unit Tests
        working-directory: ./src
        run: uv run pytest
